# Generated by Django 4.1.6 on 2023-02-04 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Характер отказа',
                'verbose_name_plural': 'Характеры отказа',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=128, verbose_name='Зав.№ машины')),
                ('number_engine', models.CharField(max_length=128, verbose_name='Зав.№ двигателя')),
                ('number_transmission', models.CharField(max_length=200, verbose_name='Зав.№ трансмиссии')),
                ('number_drive_axle', models.CharField(max_length=200, verbose_name='Зав.№ ведущего моста')),
                ('number_guiding_axle', models.CharField(max_length=200, verbose_name='Зав. № управляемого моста')),
                ('delivery_contract', models.CharField(max_length=200, verbose_name='Договор поставки №, дата')),
                ('delivery_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('recipient', models.CharField(max_length=200, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=250, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment_package', models.CharField(max_length=500, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='ModelDriveAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателя',
            },
        ),
        migrations.CreateModel(
            name='ModelGuidingAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модели управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='ModelMashine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модели техники',
            },
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'модель трансмиссии',
                'verbose_name_plural': 'модели трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='RepairingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
            },
        ),
        migrations.CreateModel(
            name='Type_Maintenance_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Вид ТО',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата отказа')),
                ('operation_time', models.IntegerField(verbose_name="verbose_name='Наработка, м/час")),
                ('description_reclamation', models.TextField(max_length=600, verbose_name='Описание отказа')),
                ('spare_part', models.TextField(max_length=250, verbose_name='Используемые запасные части')),
                ('reinstatement_date', models.DateField(verbose_name='Дата восстановления')),
                ('failure_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.failuredescription', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.machine', verbose_name='Машина')),
                ('repairing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.repairingtype', verbose_name='Способ восстановления')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламация',
            },
        ),
        migrations.CreateModel(
            name='Maintenance_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maintenance_operation', models.DateField(verbose_name='Дата проведения ТО')),
                ('operation_time', models.IntegerField(verbose_name="verbose_name='Наработка, м/час")),
                ('number_workshop_order', models.CharField(max_length=50, verbose_name='№ заказ-наряда')),
                ('date_workshop_order', models.DateField(verbose_name='дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.machine', verbose_name='Машина')),
                ('services_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО')),
                ('type_maintenance_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.type_maintenance_operation', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Техническое обслуживание',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='model_drive_axle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.modeldriveaxle', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.modelengine', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_guiding_axle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.modelguidingaxle', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_mashine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.modelmashine', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.modeltransmission', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='machine',
            name='services_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
