# Generated by Django 4.1.6 on 2023-02-08 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='services_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО'),
        ),
    ]
