# Generated by Django 4.1.6 on 2023-02-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_maintenance_operation_operation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='slug',
        ),
    ]
