# Generated by Django 4.1.6 on 2023-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_machine_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_operation',
            name='operation_time',
            field=models.IntegerField(null=True, verbose_name='Наработка, м/час'),
        ),
    ]
